name: Terraform Deployment Automation

on:
  push:
    branches:
      - main  # Jab bhi main branch par push hoga tabhi chalega

jobs:
  terraform:
    name: 'Terraform Run'
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub par tumhara code checkout karega
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Azure mein tumhare secret password se login karega
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Terraform setup karega runner machine par
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 4. Terraform init chalaega (Backend check karne ke liye)
    - name: Terraform Init
      run: terraform init

    # 5. automatically terraform apply chala dega
    - name: Terraform Apply
      run: terraform apply -auto-approve